# ===========================
# APPLICATION
# ===========================
spring.application.name=banking-app
server.port=8080

# ===========================
# SQLITE DATABASE
# ===========================
spring.datasource.url=jdbc:sqlite:bankingdb.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect